"""update tags primary keys

Revision ID: 0968eddf5326
Revises: 7553371ffb60
Create Date: 2017-09-21 20:56:07.433415

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0968eddf5326'
down_revision = '7553371ffb60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('connections', sa.Column('id', sa.Integer(), nullable=False))
    op.alter_column('connections', 'user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('connections', 'user_tag_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.add_column('post_connections', sa.Column('id', sa.Integer(), nullable=False))
    op.alter_column('post_connections', 'post_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('post_connections', 'post_tag_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('post_connections', 'post_tag_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('post_connections', 'post_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.drop_column('post_connections', 'id')
    op.alter_column('connections', 'user_tag_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('connections', 'user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.drop_column('connections', 'id')
    # ### end Alembic commands ###
