"""add publish date for post

Revision ID: 5e927407eb07
Revises: 0968eddf5326
Create Date: 2017-09-21 21:22:40.965080

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5e927407eb07'
down_revision = '0968eddf5326'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('connections', 'user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('connections', 'user_tag_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('post_connections', 'post_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('post_connections', 'post_tag_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.add_column('posts', sa.Column('published', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_posts_published'), 'posts', ['published'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_posts_published'), table_name='posts')
    op.drop_column('posts', 'published')
    op.alter_column('post_connections', 'post_tag_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('post_connections', 'post_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('connections', 'user_tag_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('connections', 'user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    # ### end Alembic commands ###
